name: CI - lit-based Testing

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: papychacal/xdsl-llvm:98e674c9f16d677d95c67bc130e267fae331e43c
    steps:
    - name: Checkout Devito
      uses: actions/checkout@v4

    - name: Upgrade pip
      run: |
        pip install --upgrade pip

    - name: Install requirements and xDSL
      run: |
        pip install git+https://github.com/xdslproject/xdsl@f8bb935880276cf077e0a80f1905105d0a98eb33
        pip install -e .[tests]

    - name: Execute lit tests
      run: |
        lit -v tests/filecheck/
